// biome-ignore-all lint: generated by TanStack Router

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/root";
import { Route as reposRouteImport } from "./routes/repos";
import { Route as shellRouteImport } from "./routes/shell";
import { Route as reposDotrepoIdRouteImport } from "./routes/repos.$repoId";
import { Route as inviteDotcodeRouteImport } from "./routes/invite.$code";
import { Route as settingsRouteImport } from "./routes/settings";
import { Route as homeRouteImport } from "./routes/home";
import { Route as cRouteImport } from "./routes/c";
import { Route as indexRouteImport } from "./routes/index";
import { Route as chatDotchannelIdRouteImport } from "./routes/chat.$channelId";
import { Route as reposDotrepoIdDotblobDotsplatRouteImport } from "./routes/repos.$repoId.blob.$";

const reposRoute = reposRouteImport.update({
  id: "/repos",
  path: "/repos",
  getParentRoute: () => rootRouteImport,
} as any);
const shellRoute = shellRouteImport.update({
  id: "/_shell",
  getParentRoute: () => rootRouteImport,
} as any);
const reposDotrepoIdRoute = reposDotrepoIdRouteImport.update({
  id: "/repos/$repoId",
  path: "/repos/$repoId",
  getParentRoute: () => rootRouteImport,
} as any);
const inviteDotcodeRoute = inviteDotcodeRouteImport.update({
  id: "/invite/$code",
  path: "/invite/$code",
  getParentRoute: () => rootRouteImport,
} as any);
const settingsRoute = settingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => shellRoute,
} as any);
const homeRoute = homeRouteImport.update({
  id: "/home",
  path: "/home",
  getParentRoute: () => shellRoute,
} as any);
const cRoute = cRouteImport.update({
  id: "/c",
  path: "/c",
  getParentRoute: () => shellRoute,
} as any);
const indexRoute = indexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => shellRoute,
} as any);
const chatDotchannelIdRoute = chatDotchannelIdRouteImport.update({
  id: "/c/$channelId",
  path: "/c/$channelId",
  getParentRoute: () => shellRoute,
} as any);
const reposDotrepoIdDotblobDotsplatRoute =
  reposDotrepoIdDotblobDotsplatRouteImport.update({
    id: "/repos/$repoId/blob/$",
    path: "/repos/$repoId/blob/$",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof indexRoute;
  "/repos": typeof reposRoute;
  "/c": typeof cRoute;
  "/home": typeof homeRoute;
  "/settings": typeof settingsRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/c/$channelId": typeof chatDotchannelIdRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRoutesByTo {
  "/repos": typeof reposRoute;
  "/": typeof indexRoute;
  "/c": typeof cRoute;
  "/home": typeof homeRoute;
  "/settings": typeof settingsRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/c/$channelId": typeof chatDotchannelIdRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_shell": typeof shellRouteWithChildren;
  "/repos": typeof reposRoute;
  "/_shell/": typeof indexRoute;
  "/_shell/c": typeof cRoute;
  "/_shell/home": typeof homeRoute;
  "/_shell/settings": typeof settingsRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/_shell/c/$channelId": typeof chatDotchannelIdRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/repos"
    | "/c"
    | "/home"
    | "/settings"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/c/$channelId"
    | "/repos/$repoId/blob/$";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/repos"
    | "/"
    | "/c"
    | "/home"
    | "/settings"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/c/$channelId"
    | "/repos/$repoId/blob/$";
  id:
    | "__root__"
    | "/_shell"
    | "/repos"
    | "/_shell/"
    | "/_shell/c"
    | "/_shell/home"
    | "/_shell/settings"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/_shell/c/$channelId"
    | "/repos/$repoId/blob/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  shellRoute: typeof shellRouteWithChildren;
  reposRoute: typeof reposRoute;
  inviteDotcodeRoute: typeof inviteDotcodeRoute;
  reposDotrepoIdRoute: typeof reposDotrepoIdRoute;
  reposDotrepoIdDotblobDotsplatRoute: typeof reposDotrepoIdDotblobDotsplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/repos": {
      id: "/repos";
      path: "/repos";
      fullPath: "/repos";
      preLoaderRoute: typeof reposRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_shell": {
      id: "/_shell";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof shellRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/$repoId": {
      id: "/repos/$repoId";
      path: "/repos/$repoId";
      fullPath: "/repos/$repoId";
      preLoaderRoute: typeof reposDotrepoIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/invite/$code": {
      id: "/invite/$code";
      path: "/invite/$code";
      fullPath: "/invite/$code";
      preLoaderRoute: typeof inviteDotcodeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_shell/settings": {
      id: "/_shell/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof settingsRouteImport;
      parentRoute: typeof shellRoute;
    };
    "/_shell/home": {
      id: "/_shell/home";
      path: "/home";
      fullPath: "/home";
      preLoaderRoute: typeof homeRouteImport;
      parentRoute: typeof shellRoute;
    };
    "/_shell/c": {
      id: "/_shell/c";
      path: "/c";
      fullPath: "/c";
      preLoaderRoute: typeof cRouteImport;
      parentRoute: typeof shellRoute;
    };
    "/_shell/": {
      id: "/_shell/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof shellRoute;
    };
    "/_shell/c/$channelId": {
      id: "/_shell/c/$channelId";
      path: "/c/$channelId";
      fullPath: "/c/$channelId";
      preLoaderRoute: typeof chatDotchannelIdRouteImport;
      parentRoute: typeof shellRoute;
    };
    "/repos/$repoId/blob/$": {
      id: "/repos/$repoId/blob/$";
      path: "/repos/$repoId/blob/$";
      fullPath: "/repos/$repoId/blob/$";
      preLoaderRoute: typeof reposDotrepoIdDotblobDotsplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface shellRouteChildren {
  indexRoute: typeof indexRoute;
  cRoute: typeof cRoute;
  homeRoute: typeof homeRoute;
  settingsRoute: typeof settingsRoute;
  chatDotchannelIdRoute: typeof chatDotchannelIdRoute;
}

const shellRouteChildren: shellRouteChildren = {
  indexRoute: indexRoute,
  cRoute: cRoute,
  homeRoute: homeRoute,
  settingsRoute: settingsRoute,
  chatDotchannelIdRoute: chatDotchannelIdRoute,
};

const shellRouteWithChildren = shellRoute._addFileChildren(shellRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  shellRoute: shellRouteWithChildren,
  reposRoute: reposRoute,
  inviteDotcodeRoute: inviteDotcodeRoute,
  reposDotrepoIdRoute: reposDotrepoIdRoute,
  reposDotrepoIdDotblobDotsplatRoute: reposDotrepoIdDotblobDotsplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
